// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nilda.EntityFramework;

namespace Nilda.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210725095125_AddDefaultSeedDataForCountry")]
    partial class AddDefaultSeedDataForCountry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.Barangay", b =>
                {
                    b.Property<int>("BarangayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistrictOrTownId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("BarangayId");

                    b.HasIndex("DistrictOrTownId");

                    b.ToTable("Barangays");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryRegionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryRegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDefault")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 2,
                            CountryCode = "BD",
                            Name = "Bangladesh",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 3,
                            CountryCode = "BE",
                            Name = "Belgium",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 4,
                            CountryCode = "BF",
                            Name = "Burkina Faso",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 5,
                            CountryCode = "BG",
                            Name = "Bulgaria",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 6,
                            CountryCode = "BA",
                            Name = "Bosnia and Herzegovina",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 7,
                            CountryCode = "BB",
                            Name = "Barbados",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 8,
                            CountryCode = "WF",
                            Name = "Wallis and Futuna",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 9,
                            CountryCode = "BL",
                            Name = "Saint Barthelemy",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 10,
                            CountryCode = "BM",
                            Name = "Bermuda",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 11,
                            CountryCode = "BN",
                            Name = "Brunei",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 12,
                            CountryCode = "BO",
                            Name = "Bolivia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 13,
                            CountryCode = "BH",
                            Name = "Bahrain",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 14,
                            CountryCode = "BI",
                            Name = "Burundi",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 15,
                            CountryCode = "BJ",
                            Name = "Benin",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 16,
                            CountryCode = "BT",
                            Name = "Bhutan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 17,
                            CountryCode = "JM",
                            Name = "Jamaica",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 18,
                            CountryCode = "BV",
                            Name = "Bouvet Island",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 19,
                            CountryCode = "BW",
                            Name = "Botswana",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 20,
                            CountryCode = "WS",
                            Name = "Samoa",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 21,
                            CountryCode = "BQ",
                            Name = "Bonaire, Saint Eustatius and Saba ",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 22,
                            CountryCode = "BR",
                            Name = "Brazil",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 23,
                            CountryCode = "BS",
                            Name = "Bahamas",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 24,
                            CountryCode = "JE",
                            Name = "Jersey",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 25,
                            CountryCode = "BY",
                            Name = "Belarus",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 26,
                            CountryCode = "BZ",
                            Name = "Belize",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 27,
                            CountryCode = "RU",
                            Name = "Russia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 28,
                            CountryCode = "RW",
                            Name = "Rwanda",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 29,
                            CountryCode = "RS",
                            Name = "Serbia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 30,
                            CountryCode = "TL",
                            Name = "East Timor",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 31,
                            CountryCode = "RE",
                            Name = "Reunion",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 32,
                            CountryCode = "TM",
                            Name = "Turkmenistan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 33,
                            CountryCode = "TJ",
                            Name = "Tajikistan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 34,
                            CountryCode = "RO",
                            Name = "Romania",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 35,
                            CountryCode = "TK",
                            Name = "Tokelau",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 36,
                            CountryCode = "GW",
                            Name = "Guinea-Bissau",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 37,
                            CountryCode = "GU",
                            Name = "Guam",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 38,
                            CountryCode = "GT",
                            Name = "Guatemala",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 39,
                            CountryCode = "GS",
                            Name = "South Georgia and the South Sandwich Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 40,
                            CountryCode = "GR",
                            Name = "Greece",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 41,
                            CountryCode = "GQ",
                            Name = "Equatorial Guinea",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 42,
                            CountryCode = "GP",
                            Name = "Guadeloupe",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 43,
                            CountryCode = "JP",
                            Name = "Japan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 44,
                            CountryCode = "GY",
                            Name = "Guyana",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 45,
                            CountryCode = "GG",
                            Name = "Guernsey",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 46,
                            CountryCode = "GF",
                            Name = "French Guiana",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 47,
                            CountryCode = "GE",
                            Name = "Georgia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 48,
                            CountryCode = "GD",
                            Name = "Grenada",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 49,
                            CountryCode = "GB",
                            Name = "United Kingdom",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 50,
                            CountryCode = "GA",
                            Name = "Gabon",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 51,
                            CountryCode = "SV",
                            Name = "El Salvador",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 52,
                            CountryCode = "GN",
                            Name = "Guinea",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 53,
                            CountryCode = "GM",
                            Name = "Gambia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 54,
                            CountryCode = "GL",
                            Name = "Greenland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 55,
                            CountryCode = "GI",
                            Name = "Gibraltar",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 56,
                            CountryCode = "GH",
                            Name = "Ghana",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 57,
                            CountryCode = "OM",
                            Name = "Oman",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 58,
                            CountryCode = "TN",
                            Name = "Tunisia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 59,
                            CountryCode = "JO",
                            Name = "Jordan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 60,
                            CountryCode = "HR",
                            Name = "Croatia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 61,
                            CountryCode = "HT",
                            Name = "Haiti",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 62,
                            CountryCode = "HU",
                            Name = "Hungary",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 63,
                            CountryCode = "HK",
                            Name = "Hong Kong",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 64,
                            CountryCode = "HN",
                            Name = "Honduras",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 65,
                            CountryCode = "HM",
                            Name = "Heard Island and McDonald Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 66,
                            CountryCode = "VE",
                            Name = "Venezuela",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 67,
                            CountryCode = "PR",
                            Name = "Puerto Rico",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 68,
                            CountryCode = "PS",
                            Name = "Palestinian Territory",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 69,
                            CountryCode = "PW",
                            Name = "Palau",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 70,
                            CountryCode = "PT",
                            Name = "Portugal",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 71,
                            CountryCode = "SJ",
                            Name = "Svalbard and Jan Mayen",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 72,
                            CountryCode = "PY",
                            Name = "Paraguay",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 73,
                            CountryCode = "IQ",
                            Name = "Iraq",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 74,
                            CountryCode = "PA",
                            Name = "Panama",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 75,
                            CountryCode = "PF",
                            Name = "French Polynesia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 76,
                            CountryCode = "PG",
                            Name = "Papua New Guinea",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 77,
                            CountryCode = "PE",
                            Name = "Peru",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 78,
                            CountryCode = "PK",
                            Name = "Pakistan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 79,
                            CountryCode = "PH",
                            Name = "Philippines",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 80,
                            CountryCode = "PN",
                            Name = "Pitcairn",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 81,
                            CountryCode = "PL",
                            Name = "Poland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 82,
                            CountryCode = "PM",
                            Name = "Saint Pierre and Miquelon",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 83,
                            CountryCode = "ZM",
                            Name = "Zambia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 84,
                            CountryCode = "EH",
                            Name = "Western Sahara",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 85,
                            CountryCode = "EE",
                            Name = "Estonia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 86,
                            CountryCode = "EG",
                            Name = "Egypt",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 87,
                            CountryCode = "ZA",
                            Name = "South Africa",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 88,
                            CountryCode = "EC",
                            Name = "Ecuador",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 89,
                            CountryCode = "IT",
                            Name = "Italy",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 90,
                            CountryCode = "VN",
                            Name = "Vietnam",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 91,
                            CountryCode = "SB",
                            Name = "Solomon Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 92,
                            CountryCode = "ET",
                            Name = "Ethiopia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 93,
                            CountryCode = "SO",
                            Name = "Somalia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 94,
                            CountryCode = "ZW",
                            Name = "Zimbabwe",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 95,
                            CountryCode = "SA",
                            Name = "Saudi Arabia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 96,
                            CountryCode = "ES",
                            Name = "Spain",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 97,
                            CountryCode = "ER",
                            Name = "Eritrea",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 98,
                            CountryCode = "ME",
                            Name = "Montenegro",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 99,
                            CountryCode = "MD",
                            Name = "Moldova",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 100,
                            CountryCode = "MG",
                            Name = "Madagascar",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 101,
                            CountryCode = "MF",
                            Name = "Saint Martin",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 102,
                            CountryCode = "MA",
                            Name = "Morocco",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 103,
                            CountryCode = "MC",
                            Name = "Monaco",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 104,
                            CountryCode = "UZ",
                            Name = "Uzbekistan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 105,
                            CountryCode = "MM",
                            Name = "Myanmar",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 106,
                            CountryCode = "ML",
                            Name = "Mali",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 107,
                            CountryCode = "MO",
                            Name = "Macao",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 108,
                            CountryCode = "MN",
                            Name = "Mongolia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 109,
                            CountryCode = "MH",
                            Name = "Marshall Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 110,
                            CountryCode = "MK",
                            Name = "Macedonia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 111,
                            CountryCode = "MU",
                            Name = "Mauritius",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 112,
                            CountryCode = "MT",
                            Name = "Malta",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 113,
                            CountryCode = "MW",
                            Name = "Malawi",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 114,
                            CountryCode = "MV",
                            Name = "Maldives",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 115,
                            CountryCode = "MQ",
                            Name = "Martinique",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 116,
                            CountryCode = "MP",
                            Name = "Northern Mariana Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 117,
                            CountryCode = "MS",
                            Name = "Montserrat",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 118,
                            CountryCode = "MR",
                            Name = "Mauritania",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 119,
                            CountryCode = "IM",
                            Name = "Isle of Man",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 120,
                            CountryCode = "UG",
                            Name = "Uganda",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 121,
                            CountryCode = "TZ",
                            Name = "Tanzania",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 122,
                            CountryCode = "MY",
                            Name = "Malaysia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 123,
                            CountryCode = "MX",
                            Name = "Mexico",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 124,
                            CountryCode = "IL",
                            Name = "Israel",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 125,
                            CountryCode = "FR",
                            Name = "France",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 126,
                            CountryCode = "IO",
                            Name = "British Indian Ocean Territory",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 127,
                            CountryCode = "SH",
                            Name = "Saint Helena",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 128,
                            CountryCode = "FI",
                            Name = "Finland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 129,
                            CountryCode = "FJ",
                            Name = "Fiji",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 130,
                            CountryCode = "FK",
                            Name = "Falkland Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 131,
                            CountryCode = "FM",
                            Name = "Micronesia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 132,
                            CountryCode = "FO",
                            Name = "Faroe Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 133,
                            CountryCode = "NI",
                            Name = "Nicaragua",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 134,
                            CountryCode = "NL",
                            Name = "Netherlands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 135,
                            CountryCode = "NO",
                            Name = "Norway",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 136,
                            CountryCode = "NA",
                            Name = "Namibia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 137,
                            CountryCode = "VU",
                            Name = "Vanuatu",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 138,
                            CountryCode = "NC",
                            Name = "New Caledonia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 139,
                            CountryCode = "NE",
                            Name = "Niger",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 140,
                            CountryCode = "NF",
                            Name = "Norfolk Island",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 141,
                            CountryCode = "NG",
                            Name = "Nigeria",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 142,
                            CountryCode = "NZ",
                            Name = "New Zealand",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 143,
                            CountryCode = "NP",
                            Name = "Nepal",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 144,
                            CountryCode = "NR",
                            Name = "Nauru",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 145,
                            CountryCode = "NU",
                            Name = "Niue",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 146,
                            CountryCode = "CK",
                            Name = "Cook Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 147,
                            CountryCode = "XK",
                            Name = "Kosovo",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 148,
                            CountryCode = "CI",
                            Name = "Ivory Coast",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 149,
                            CountryCode = "CH",
                            Name = "Switzerland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 150,
                            CountryCode = "CO",
                            Name = "Colombia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 151,
                            CountryCode = "CN",
                            Name = "China",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 152,
                            CountryCode = "CM",
                            Name = "Cameroon",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 153,
                            CountryCode = "CL",
                            Name = "Chile",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 154,
                            CountryCode = "CC",
                            Name = "Cocos Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 155,
                            CountryCode = "CA",
                            Name = "Canada",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 156,
                            CountryCode = "CG",
                            Name = "Republic of the Congo",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 157,
                            CountryCode = "CF",
                            Name = "Central African Republic",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 158,
                            CountryCode = "CD",
                            Name = "Democratic Republic of the Congo",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 159,
                            CountryCode = "CZ",
                            Name = "Czech Republic",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 160,
                            CountryCode = "CY",
                            Name = "Cyprus",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 161,
                            CountryCode = "CX",
                            Name = "Christmas Island",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 162,
                            CountryCode = "CR",
                            Name = "Costa Rica",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 163,
                            CountryCode = "CW",
                            Name = "Curacao",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 164,
                            CountryCode = "CV",
                            Name = "Cape Verde",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 165,
                            CountryCode = "CU",
                            Name = "Cuba",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 166,
                            CountryCode = "SZ",
                            Name = "Swaziland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 167,
                            CountryCode = "SY",
                            Name = "Syria",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 168,
                            CountryCode = "SX",
                            Name = "Sint Maarten",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 169,
                            CountryCode = "KG",
                            Name = "Kyrgyzstan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 170,
                            CountryCode = "KE",
                            Name = "Kenya",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 171,
                            CountryCode = "SS",
                            Name = "South Sudan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 172,
                            CountryCode = "SR",
                            Name = "Suriname",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 173,
                            CountryCode = "KI",
                            Name = "Kiribati",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 174,
                            CountryCode = "KH",
                            Name = "Cambodia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 175,
                            CountryCode = "KN",
                            Name = "Saint Kitts and Nevis",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 176,
                            CountryCode = "KM",
                            Name = "Comoros",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 177,
                            CountryCode = "ST",
                            Name = "Sao Tome and Principe",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 178,
                            CountryCode = "SK",
                            Name = "Slovakia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 179,
                            CountryCode = "KR",
                            Name = "South Korea",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 180,
                            CountryCode = "SI",
                            Name = "Slovenia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 181,
                            CountryCode = "KP",
                            Name = "North Korea",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 182,
                            CountryCode = "KW",
                            Name = "Kuwait",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 183,
                            CountryCode = "SN",
                            Name = "Senegal",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 184,
                            CountryCode = "SM",
                            Name = "San Marino",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 185,
                            CountryCode = "SL",
                            Name = "Sierra Leone",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 186,
                            CountryCode = "SC",
                            Name = "Seychelles",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 187,
                            CountryCode = "KZ",
                            Name = "Kazakhstan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 188,
                            CountryCode = "KY",
                            Name = "Cayman Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 189,
                            CountryCode = "SG",
                            Name = "Singapore",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 190,
                            CountryCode = "SE",
                            Name = "Sweden",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 191,
                            CountryCode = "SD",
                            Name = "Sudan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 192,
                            CountryCode = "DO",
                            Name = "Dominican Republic",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 193,
                            CountryCode = "DM",
                            Name = "Dominica",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 194,
                            CountryCode = "DJ",
                            Name = "Djibouti",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 195,
                            CountryCode = "DK",
                            Name = "Denmark",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 196,
                            CountryCode = "VG",
                            Name = "British Virgin Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 197,
                            CountryCode = "DE",
                            Name = "Germany",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 198,
                            CountryCode = "YE",
                            Name = "Yemen",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 199,
                            CountryCode = "DZ",
                            Name = "Algeria",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 200,
                            CountryCode = "US",
                            Name = "United States",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 201,
                            CountryCode = "UY",
                            Name = "Uruguay",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 202,
                            CountryCode = "YT",
                            Name = "Mayotte",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 203,
                            CountryCode = "UM",
                            Name = "United States Minor Outlying Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 204,
                            CountryCode = "LB",
                            Name = "Lebanon",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 205,
                            CountryCode = "LC",
                            Name = "Saint Lucia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 206,
                            CountryCode = "LA",
                            Name = "Laos",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 207,
                            CountryCode = "TV",
                            Name = "Tuvalu",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 208,
                            CountryCode = "TW",
                            Name = "Taiwan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 209,
                            CountryCode = "TT",
                            Name = "Trinidad and Tobago",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 210,
                            CountryCode = "TR",
                            Name = "Turkey",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 211,
                            CountryCode = "LK",
                            Name = "Sri Lanka",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 212,
                            CountryCode = "LI",
                            Name = "Liechtenstein",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 213,
                            CountryCode = "LV",
                            Name = "Latvia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 214,
                            CountryCode = "TO",
                            Name = "Tonga",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 215,
                            CountryCode = "LT",
                            Name = "Lithuania",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 216,
                            CountryCode = "LU",
                            Name = "Luxembourg",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 217,
                            CountryCode = "LR",
                            Name = "Liberia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 218,
                            CountryCode = "LS",
                            Name = "Lesotho",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 219,
                            CountryCode = "TH",
                            Name = "Thailand",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 220,
                            CountryCode = "TF",
                            Name = "French Southern Territories",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 221,
                            CountryCode = "TG",
                            Name = "Togo",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 222,
                            CountryCode = "TD",
                            Name = "Chad",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 223,
                            CountryCode = "TC",
                            Name = "Turks and Caicos Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 224,
                            CountryCode = "LY",
                            Name = "Libya",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 225,
                            CountryCode = "VA",
                            Name = "Vatican",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 226,
                            CountryCode = "VC",
                            Name = "Saint Vincent and the Grenadines",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 227,
                            CountryCode = "AE",
                            Name = "United Arab Emirates",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 228,
                            CountryCode = "AD",
                            Name = "Andorra",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 229,
                            CountryCode = "AG",
                            Name = "Antigua and Barbuda",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 230,
                            CountryCode = "AF",
                            Name = "Afghanistan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 231,
                            CountryCode = "AI",
                            Name = "Anguilla",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 232,
                            CountryCode = "VI",
                            Name = "U.S. Virgin Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 233,
                            CountryCode = "IS",
                            Name = "Iceland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 234,
                            CountryCode = "IR",
                            Name = "Iran",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 235,
                            CountryCode = "AM",
                            Name = "Armenia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 236,
                            CountryCode = "AL",
                            Name = "Albania",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 237,
                            CountryCode = "AO",
                            Name = "Angola",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 238,
                            CountryCode = "AQ",
                            Name = "Antarctica",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 239,
                            CountryCode = "AS",
                            Name = "American Samoa",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 240,
                            CountryCode = "AR",
                            Name = "Argentina",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 241,
                            CountryCode = "AU",
                            Name = "Australia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 242,
                            CountryCode = "AT",
                            Name = "Austria",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 243,
                            CountryCode = "AW",
                            Name = "Aruba",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 244,
                            CountryCode = "IN",
                            Name = "India",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 245,
                            CountryCode = "AX",
                            Name = "Aland Islands",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 246,
                            CountryCode = "AZ",
                            Name = "Azerbaijan",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 247,
                            CountryCode = "IE",
                            Name = "Ireland",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 248,
                            CountryCode = "ID",
                            Name = "Indonesia",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 249,
                            CountryCode = "UA",
                            Name = "Ukraine",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 250,
                            CountryCode = "QA",
                            Name = "Qatar",
                            isActive = false,
                            isDefault = false
                        },
                        new
                        {
                            CountryId = 251,
                            CountryCode = "MZ",
                            Name = "Mozambique",
                            isActive = false,
                            isDefault = false
                        });
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.CountryRegion", b =>
                {
                    b.Property<int>("CountryRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CountryRegionId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryRegions");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.DistrictOrTown", b =>
                {
                    b.Property<int>("DistrictOrTownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("DistrictOrTownId");

                    b.HasIndex("CityId");

                    b.ToTable("DistrictOrTowns");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.Barangay", b =>
                {
                    b.HasOne("Nilda.EntityFrameworkCore.Entities.DistrictOrTown", "DistrictOrTown")
                        .WithMany("Barangays")
                        .HasForeignKey("DistrictOrTownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistrictOrTown");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.City", b =>
                {
                    b.HasOne("Nilda.EntityFrameworkCore.Entities.CountryRegion", "CountryRegion")
                        .WithMany("Cities")
                        .HasForeignKey("CountryRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryRegion");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.CountryRegion", b =>
                {
                    b.HasOne("Nilda.EntityFrameworkCore.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.DistrictOrTown", b =>
                {
                    b.HasOne("Nilda.EntityFrameworkCore.Entities.City", "City")
                        .WithMany("DistrictOrTowns")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.City", b =>
                {
                    b.Navigation("DistrictOrTowns");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.CountryRegion", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Nilda.EntityFrameworkCore.Entities.DistrictOrTown", b =>
                {
                    b.Navigation("Barangays");
                });
#pragma warning restore 612, 618
        }
    }
}
